server:
  port: 8780
spring:
  application:
    name: order-openfeign-sentinel
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
management:
  endpoints:
    web:
      exposure:
        include: '*'
feign:
  sentinel:
    enabled: true
