server:
  port: 8182
#DB Configuration:
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seata-stock?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  application:
    name: stock-seata

mybatis:
  mapper-locations: classpath:mybatis/mapper/StockMapper.xml
  #config-location: classpath:mybatis-config.xml
  #type-aliases-package: com.example.order.pojo
  configuration:
    map-underscore-to-camel-case: true
